---
controller_execution_environments:
  - name: ansible-automation-platform-24/ee-supported-rhel8
    organization: IT Service Automation
    image: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8
    pull: missing
    credential: registry.redhat.io
  - name: hashicorp_ee
    organization: IT Service Automation
    image: quay.io/zigfreed/hashicorp_ee:latest
    pull: missing
    credential: quay.io
  - name: F5_ee
    organization: IT Service Automation
    image: quay.io/locust61/f5_ee:0.1
    pull: missing
  - name: Minimal execution environment
    organization: # Leave this empty organization to let the object_diff role to work properly
    image: registry.redhat.io/ansible-automation-platform-26/ee-minimal-rhel9@sha256:47f37cc773c8a12ec689e3a6979a1467b8973b1a9ca66a640b742d749393faa1
    pull: ""
  - name: Default execution environment
    organization: # Leave this empty organization to let the object_diff role to work properly
    image: registry.redhat.io/ansible-automation-platform-26/ee-supported-rhel9@sha256:7d1060579c139172260c3b145d1b95af2e323f73a47488427f2e3fd1af461c83
    pull: ""
  - name: Control Plane Execution Environment
    organization: # Leave this empty organization to let the object_diff role to work properly
    image: registry.redhat.io/ansible-automation-platform-26/ee-supported-rhel9@sha256:7d1060579c139172260c3b145d1b95af2e323f73a47488427f2e3fd1af461c83
    pull: ""
  - name: Product Demos EE
    organization: # Leave this empty organization to let the object_diff role to work properly
    image: quay.io/ansible-product-demos/apd-ee-25:latest
    pull: missing
  - name: filetree_ee
    organization: # Leave this empty organization to let the object_diff role to work properly
    image: quay.io/zigfreed/filetree_ee:latest
    pull: missing
    credential: quay.io
...
