---
eda_decision_environments:
  - name: Default Decision Environment
    description: my default decision environment
    image_url: registry.redhat.io/ansible-automation-platform-25/de-supported-rhel8:latest
    organization: IT Service Automation
    eda_credential: registry.redhat.io
...
