---
- name: Export controller configs
  hosts: localhost
  connection: local
  gather_facts: False
  environment:
    CONTROLLER_OPTIONAL_API_URLPATTERN_PREFIX: '/api/controller/'
    AWXKIT_API_BASE_PATH: '/api/controller/'

  tasks:

    # fail with good error for Automation controller user
    - name: Determine that both AAP and Machine credentials are set
      ansible.builtin.assert:
        that:
          - "lookup('ansible.builtin.env', 'CONTROLLER_USERNAME') !=''"
          - "lookup('ansible.builtin.env', 'CONTROLLER_HOST') !=''"
          - "lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD') !=''"
        fail_msg:
          - "Red Hat Ansible Automation Platform credential is not set"
          - "Please assign correct credentials to the Job Template"

    - name: Create a new token
      ansible.platform.token:
        aap_hostname: "{{ lookup('ansible.builtin.env', 'CONTROLLER_HOST') }}"
        aap_username: "{{ lookup('ansible.builtin.env', 'CONTROLLER_USERNAME') }}"
        aap_password: "{{ lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD') }}"
        aap_validate_certs: false
        description: Controller export
        scope: write
        state: present

    - name: Printout my token
      ansible.builtin.debug:
        msg:
          - "{{ ansible_facts['aap_token']['token'] }}"
          - "{{ aap_username }}"

    - name: Export all assets
      register: controller_config
      ansible.controller.export:
        workflow_job_templates: "Run Linux Patching Workflow"
        validate_certs: False
        aap_token: "{{ ansible_facts['aap_token']['token'] }}"

    - name: Remove my token
      ansible.platform.token:
        aap_hostname: "{{ lookup('ansible.builtin.env', 'CONTROLLER_HOST') }}"
        existing_token: "{{ ansible_facts['aap_token'] }}"
        aap_token: "{{ ansible_facts['aap_token']['token'] }}"
        aap_validate_certs: false
        state: absent