---
- name: Export controller configs
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    # fail with good error for Automation controller user
    - name: Determine that both AAP and Machine credentials are set
      ansible.builtin.assert:
        that:
          - "lookup('ansible.builtin.env', 'CONTROLLER_USERNAME') !=''"
          - "lookup('ansible.builtin.env', 'CONTROLLER_HOST') !=''"
          - "lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD') !=''"
        fail_msg:
          - "Red Hat Ansible Automation Platform credential is not set"
          - "Please assign correct credentials to the Job Template"

    - name: Create a new token
      ansible.platform.token:
        aap_hostname: "{{ lookup('ansible.builtin.env', 'CONTROLLER_HOST') }}"
        aap_username: "{{ lookup('ansible.builtin.env', 'CONTROLLER_USERNAME') }}"
        aap_password: "{{ lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD') }}"
        aap_validate_certs: false
        description: Controller export
        scope: write
        state: present

    - name: Printout my token
      ansible.builtin.debug:
        msg:
          - "{{ ansible_facts['aap_token']['token'] }}"
          - "{{ aap_username }}"

    - name: "Set the oauth token to be used since now"
      ansible.builtin.set_fact:
        aap_oauthtoken: "{{ ansible_facts['aap_token']['token'] }}"
        # aap_oauthtoken_url: "{{ authtoken_res.json.url }}"

    - name: Create our directory
      ansible.builtin.file:
        path: "{{ playbook_dir }}/filetree_output"
        state: directory
        mode: '0755'

    - name: Export all objects
      vars:
        output_path: "{{ playbook_dir }}/filetree_output"
        input_tag:
          - all
        valid_tags:
          - all
          - controller_projects
      ansible.builtin.include_role:
        name: infra.aap_configuration_extended.filetree_create

    - name: Find /tmp/filetree_output
      ansible.builtin.find:
        paths: "{{ playbook_dir }}/filetree_output"
        recurse: yes
        file_type: directory

    - name: Remove my token
      ansible.platform.token:
        aap_hostname: "{{ lookup('ansible.builtin.env', 'CONTROLLER_HOST') }}"
        existing_token: "{{ ansible_facts['aap_token'] }}"
        aap_token: "{{ ansible_facts['aap_token']['token'] }}"
        aap_validate_certs: false
        state: absent